addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

/**
 * Fetch and log a request
 * @param {Request} request
 */
async function handleRequest(request) {

  // 'greet' function exported from ../src/lib.rs
  const { greet } = wasm_bindgen;

  // 'wasm' binding name autogenerated by wrangler
  await wasm_bindgen(wasm)

  const greeting = greet()
  return new Response(greeting, { status: 200 })
}
